## 07. 원근변환

In [2]:
import cv2
import numpy as np
CARD = "../images/card.jpg"

In [4]:
img = cv2.imread(CARD)

# 카드를 변행해서 맞출 틀의 크기
width, height = 600, 350 # 사이즈 얼마든지 변경 가능
# 변형할 지점 선택 : 시계방향
src = np.array([[54, 261], [981, 128], [1213, 560], [194, 735]], dtype=np.float32) # 원본에서 변형하기 싶은 파트의 4개 좌표점

# 결과물 출력할 형태 : 시계방향
dst = np.array([[0, 0], [width, 0], [width, height], [0, height]], dtype=np.float32) # 0,0 가로, 가로세로, 세로. src의 점들에 맞추어서 좌표 찍어야 함

#원근을 변형하기 위한 matrix생성
mat = cv2.getPerspectiveTransform(src, dst)
print(mat)

# img를 mat에 의해 변환
result = cv2.warpPerspective(img, mat, (width, height)) 

cv2.imshow("img", img)
cv2.imshow("perspective", result)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 6.28270120e-01 -1.85565014e-01  1.45058823e+01]
 [ 1.20997970e-01  8.43346752e-01 -2.26647393e+02]
 [-2.25609902e-05  2.65181603e-04  1.00000000e+00]]


## 실습1 이미지 원근 변환하기
- 기울어진 이미지 다운로드
- 학습한 원근 변환 방법을 바탕으로 이미지 펼쳐보기

In [7]:
img = cv2.imread("../images/squidward.jpg")

width, height = 400, 200
src = np.array([[15, 92], [213, 16], [309, 104], [149, 170]], dtype=np.float32)
dst = np.array([[0, 0], [width, 0], [width, height], [0, height]], dtype=np.float32)

mat = cv2.getPerspectiveTransform(src, dst)
result = cv2.warpPerspective(img, mat, (width, height))

cv2.imshow("img", img)
cv2.imshow("perspective", result)

cv2.waitKey(0)
cv2.destroyAllWindows()