### 01. pytorch import 및 버전 확인

In [2]:
import torch

torch.__version__

import numpy as np

device 

## 1. 텐서(Tensor) 초기화
- 초기화 - 텐서에 특정한 값을 넣어 생성

### 1-1. 초기화 되지 않은 텐서
- 특정한 값이 채워지지 않은 상태로 생성하는 것

In [4]:
tensor = torch.empty(4, 2)
print(tensor)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### 1-2. 상수로 초기화된 텐서
- torch.zeros()
- torch.ones()

In [5]:
a = torch.zeros(2, 2)
b = torch.ones(3, 4)
print(a)
print(b)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### 1-3. 무작위로 초기화된 텐서
- torch.rand() - 0~1사이의 값으로 무작위로 초기화
- torch.randn() - 표준분포 상의 무작위 값으로 초기화

In [6]:
a = torch.rand(3, 3)
b = torch.randn(3, 3)
print(a)
print(b)

tensor([[6.5932e-01, 3.3560e-01, 9.6465e-01],
        [7.9919e-01, 7.4595e-04, 2.3290e-01],
        [9.5760e-01, 8.0799e-02, 6.6083e-01]])
tensor([[ 0.8231, -1.6761, -1.8932],
        [-1.1420, -0.2061, -0.2834],
        [-1.4834,  1.2768, -1.5002]])


1-4. 직접 입력한 값으로 초기화
- torch.tensor([]) - 직접 입력한 값으로 초기화

In [7]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

### 1-5. numpy 배열로부터 초기화
- from_numpy()

In [12]:
nd_arr = np.array([1, 2, 3])
print(nd_arr)

a = torch.from_numpy(nd_arr) # nd_arr로 부터 값을 직접 받아옴

b = a
new_nd = b.numpy() # tensor에서 nd array로 변환
type(new_nd)

[1 2 3]


numpy.ndarray

### 1-6. 특정 텐서와 같은 타입, 무작위로 채움
- nnn_like(tensor, data type)

In [13]:
a = torch.ones(3, 4, dtype=torch.long)
b = torch.rand_like(a, dtype=torch.float64) #값은 달라도 a와 같은 구조 가지고 있음

print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0.2740, 0.6523, 0.2055, 0.5427],
        [0.2043, 0.3938, 0.1631, 0.0482],
        [0.9810, 0.1821, 0.5032, 0.4761]])


### 실습1 - 퀴즈(1)
- 제시된 문제 풀기
- 검색하지 않고 가능한한 스스로 풀어보기

### 1-7 텐서의 속성

In [8]:
tensor = torch.rand(3, 4)
print(tensor.size()) # 사이즈. 함수로 부르기
print(tensor.shape) # 속성으로 부르기
print(tensor.dtype) # 데이터 타입
print(tensor.device)

torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu


### 1-8 특정 타입의 텐서 생성

In [11]:
tensor = torch.rand(3, 4, dtype=torch.float64)
print(tensor.dtype)

float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.dtype) 

int_tensor = torch.IntTensor([1,2,3])
print(int_tensor)
print(int_tensor.dtype)

torch.float64
torch.float32
tensor([1, 2, 3], dtype=torch.int32)
torch.int32


### 1-9 데이터 타입 캐스팅

In [12]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())

int_tensor = torch.IntTensor([1,2,3])
print(int_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


### 1-10. CUDA Tensor

In [ ]:
#print(torch.cuda.is_available()) # cuda가 작동 가능한지 여부
tensor = torch.rand(3,4, dtype=torch.float32)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # device를 if가 가능하면 그걸쓰고 아니면 else쪽

tensor = tensor.to(device)
tensor.device # type이 cpu에서 cuda로 바뀌어야 함

device(type='cuda', index=0)

### 1-11-1. 0D Tensor(Scalar)
- 하나의 값을 담고 있는 텐서

In [17]:
t0 = torch.tensor(100) # 0차원의 1개의 값을 담은 텐서

print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(100)


### 1-11-2. 1D Tensor(Vector)
- 값들을 저장하고 있는 리스트와 유사한 텐서

In [18]:
t1 = torch.tensor([1,2,3]) # 0차원의 1개의 값을 담은 텐서

print(t1.ndim) # 1 차원
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


### 1-11-3. 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두개의 축이 존재하는 텐서

In [19]:
t2 = torch.tensor([[1, 2], [3, 4]]) # 0차원의 1개의 값을 담은 텐서

print(t2.ndim) # 2 차원
print(t2.shape)
print(t2)

2
torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


### 1-11-4. 3D Tensor(Cube)
- 큐브와 같은 형태로 세개의 축이 존재

In [ ]:
t3 = torch.tensor([[[1, 2], [3, 4]],
                   [[1,2], [3,4]]
                   [[4,5], [6,7]]]) # 0차원의 1개의 값을 담은 텐서

print(t3.ndim) # 3 차원
print(t3.shape)
print(t3)