## 02. 텐서의 연산

In [2]:
import torch

### 2-1. 산술 연산

In [3]:
### 2-1. 산술 연산

tensor = torch.rand(2, 2)
print(tensor)

tensor = tensor * 2
print(tensor)

tensor([[0.6575, 0.3619],
        [0.8901, 0.1246]])
tensor([[1.3150, 0.7238],
        [1.7802, 0.2492]])


In [4]:
tensor = torch.rand(2, 2)
print(tensor)

tensor = tensor + 1
print(tensor)

tensor([[0.5852, 0.0370],
        [0.8411, 0.4257]])
tensor([[1.5852, 1.0370],
        [1.8411, 1.4257]])


In [9]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
add = torch.add(x, y)
print(x, y)

#in-place 바꿔치기 연산
print(add)
y.add_(x)
print(y)

tensor([[0.2497, 0.7214],
        [0.2025, 0.9864]]) tensor([[0.6979, 0.5188],
        [0.8628, 0.5194]])
tensor([[0.9476, 1.2402],
        [1.0653, 1.5058]])
tensor([[0.9476, 1.2402],
        [1.0653, 1.5058]])


In [11]:
# 뺴기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
sub = torch.sub(x, y)
print(x, y)
print(sub)

y.sub(x)
print(y)

tensor([[0.8425, 0.6861],
        [0.2116, 0.3500]]) tensor([[0.4816, 0.1443],
        [0.7426, 0.6037]])
tensor([[ 0.3609,  0.5418],
        [-0.5310, -0.2538]])
tensor([[0.4816, 0.1443],
        [0.7426, 0.6037]])


In [12]:
# 곱하기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
mul = torch.mul(x, y)
print(x, y)
print(mul)


tensor([[0.1388, 0.8769],
        [0.2657, 0.0862]]) tensor([[0.4991, 0.3836],
        [0.1019, 0.0089]])
tensor([[0.0693, 0.3364],
        [0.0271, 0.0008]])
