## 02. 텐서의 연산

In [2]:
import torch

### 2-1. 산술 연산

In [3]:
### 2-1. 산술 연산

tensor = torch.rand(2, 2)
print(tensor)

tensor = tensor * 2
print(tensor)

tensor([[0.6575, 0.3619],
        [0.8901, 0.1246]])
tensor([[1.3150, 0.7238],
        [1.7802, 0.2492]])


In [4]:
tensor = torch.rand(2, 2)
print(tensor)

tensor = tensor + 1
print(tensor)

tensor([[0.5852, 0.0370],
        [0.8411, 0.4257]])
tensor([[1.5852, 1.0370],
        [1.8411, 1.4257]])


In [9]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
add = torch.add(x, y)
print(x, y)

#in-place 바꿔치기 연산
print(add)
y.add_(x)
print(y)

tensor([[0.2497, 0.7214],
        [0.2025, 0.9864]]) tensor([[0.6979, 0.5188],
        [0.8628, 0.5194]])
tensor([[0.9476, 1.2402],
        [1.0653, 1.5058]])
tensor([[0.9476, 1.2402],
        [1.0653, 1.5058]])


In [11]:
# 뺴기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
sub = torch.sub(x, y)
print(x, y)
print(sub)

y.sub(x)
print(y)

tensor([[0.8425, 0.6861],
        [0.2116, 0.3500]]) tensor([[0.4816, 0.1443],
        [0.7426, 0.6037]])
tensor([[ 0.3609,  0.5418],
        [-0.5310, -0.2538]])
tensor([[0.4816, 0.1443],
        [0.7426, 0.6037]])


In [12]:
# 곱하기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
mul = torch.mul(x, y)
print(x, y)
print(mul)


tensor([[0.1388, 0.8769],
        [0.2657, 0.0862]]) tensor([[0.4991, 0.3836],
        [0.1019, 0.0089]])
tensor([[0.0693, 0.3364],
        [0.0271, 0.0008]])


In [ ]:
#절대값
a = torch.tensor(-10)
print("절대값", torch.abs(a))

b = torch.tensor(3.3)
print("올림", torch.ceil(b))
print("반올림", torch.round(b))
print("내림", torch.floor(b))

c = torch.rand(2,2)
print("클램프", torch.clamp(c, -0.5, 0.5)) # 최대값과 최소값 지정하고 초과/미만의 tensor 값을 거기에 맞춤

절대값 tensor(10)
올림 tensor(4.)
반올림 tensor(3.)
내림 tensor(3.)
클램프 tensor([[0.2458, 0.5000],
        [0.5000, 0.3312]])


In [9]:
x = torch.randn(2, 2)
y = torch.tensor([[1, 2], [3,4]])
#최대, 최소,평균, 표준편차
print("최소값", torch.min(x))
print("최대값", torch.max(x))
print("평균", torch.mean(x))
print("표준편차", torch.std(x))

#값들의 합
print("모든 원소의 합", torch.sum(x))
# dim 0 = 열들에 맞추어서 더하기 실행
# dim 1 = 같은 행에 있는 것들을 전부 더함
print("모든 원소의 합", torch.sum(y, dim=1))

print("중복된 값 제거", torch.unique(torch.tensor([1,1,1,2,2,2,3,3,3,4,4,4,4])))

최소값 tensor(-0.9408)
최대값 tensor(1.9532)
평균 tensor(0.4829)
표준편차 tensor(1.5357)
모든 원소의 합 tensor(1.9317)
모든 원소의 합 tensor([3, 7])
중복된 값 제거 tensor([1, 2, 3, 4])


### 2-3 내적(dot product)

In [10]:
# 행렬의 연산
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

result = torch.matmul(x, y)
print(result)

tensor([[19, 22],
        [43, 50]])


### 퀴즈2
- 연산자를 풀어보아요!