In [1]:
import torch

In [ ]:
## 03. Tensor의 조작

### 3-1. 인덱싱, 슬라이싱
- numpy 처럼 활용

In [5]:
tensor = torch.tensor([[1,2], [3,4]])
print(tensor[0, 1])
print(tensor[0, :])

a = torch.tensor([1,2,3,4,5])
print(a[-2:])

b = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

c = b[b > 5]
print(c)
d = b[b % 2 == 0]
print(d)

e = b[[0,1], [1,2]] # 0행의 1번, 1행의 2번
print(e)

tensor(2)
tensor([1, 2])
tensor([4, 5])
tensor([6, 7, 8, 9])
tensor([2, 4, 6, 8])
tensor([2, 6])


### 실습 - 퀴즈3

### 3-2. Tensor의 크기, 모양 변경

In [2]:
t = torch.rand(4, 5)
x = t.view(5, 4) # 4x5 형태를 5x4류 바꿈
# 행열 곱한 값이 같아야함
y = t.view(10, 2)

### 3-3. Tensor의 숫자값 얻기

In [3]:
x = torch.tensor(10)
print(x.item())

y = torch.rand(1)
print(y)
print(y.item())

10
tensor([0.0986])
0.09862136840820312


### 3-4. 차원 축소와 증가
- torch.squeeze() : 크기가 1인 차원을 축소함
- torch.unsqueeze() : 지정한 위치에 새로운 차원 형셩

In [6]:
# squeeze
t = torch.rand(1, 3, 3)
t.shape

ts = torch.squeeze(t)
print(ts.shape)

torch.Size([3, 3])


In [9]:
# unsqueeze
t = torch.rand(3, 3, 3)
#print(t)
print(t.shape)

tu = torch.unsqueeze(t, 0)
print(tu.shape)
print(tu)

torch.Size([3, 3, 3])
torch.Size([1, 3, 3, 3])
tensor([[[[0.1855, 0.8442, 0.5527],
          [0.6065, 0.5883, 0.3068],
          [0.7566, 0.7490, 0.1398]],

         [[0.6955, 0.8542, 0.3577],
          [0.7650, 0.3561, 0.0564],
          [0.4838, 0.9057, 0.9642]],

         [[0.2701, 0.0495, 0.6132],
          [0.5142, 0.7629, 0.7218],
          [0.5742, 0.6217, 0.1784]]]])


### 3-5. Tensor간 결합

- torch.stack() : 동일한 형식의 텐서를 새롭게 그룹화 함

In [15]:
x = torch.tensor([[1,2], [3,4]])
y = torch.tensor([[5,6], [7,8]])

t = torch.stack([x,y])
print(t)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [25]:
# 기존 그룹 갯수만큼 쪼개기
t = torch.tensor([[1,2], [3,4], [5,6]])
print(t)

a, b, c = torch.chunk(t, 3, dim=0)
print(a)
print(b)
print(c)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2]])
tensor([[3, 4]])
tensor([[5, 6]])


In [27]:
# 기존 그룹 덩어리 단위로 쪼개기

t = torch.rand(3, 6)
print(t)

x, y = torch.split(t, 3, dim=1) # 열을 기준으로 3개씩 쪼개기. dim=1 열
print(x)
print(y)

tensor([[0.5542, 0.1422, 0.0341, 0.8121, 0.8227, 0.8062],
        [0.3616, 0.2866, 0.8171, 0.1142, 0.7593, 0.4527],
        [0.2661, 0.7982, 0.6699, 0.4326, 0.7044, 0.6123]])
tensor([[0.5542, 0.1422, 0.0341],
        [0.3616, 0.2866, 0.8171],
        [0.2661, 0.7982, 0.6699]])
tensor([[0.8121, 0.8227, 0.8062],
        [0.1142, 0.7593, 0.4527],
        [0.4326, 0.7044, 0.6123]])
