## PyTorch Quiz 2 : 연산

In [3]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [15]:
# 여기에 코드를 작성합니다
tensor = torch.tensor([2, 4, 6])
print("plus 5: ", tensor + 5)
print("minus 3: ", tensor - 3)

plus 5:  tensor([ 7,  9, 11])
minus 3:  tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [16]:
# 여기에 코드를 작성합니다
a = torch.rand(3, 3)
b = torch. rand(3, 3)

print(a)
print(b)

print("더하기: ", a + b)
print("빼기: ", a - b)
print("곱하기: ", a * b)
print("나누기: ", a / b)

tensor([[1.7321e-04, 6.4118e-01, 9.4369e-01],
        [8.2576e-01, 6.2879e-01, 8.9889e-01],
        [6.8938e-01, 8.1050e-01, 3.4605e-01]])
tensor([[0.5418, 0.6056, 0.1441],
        [0.3898, 0.9041, 0.5123],
        [0.3373, 0.7555, 0.4511]])
더하기:  tensor([[0.5420, 1.2468, 1.0878],
        [1.2156, 1.5329, 1.4112],
        [1.0267, 1.5660, 0.7971]])
빼기:  tensor([[-0.5416,  0.0356,  0.7996],
        [ 0.4359, -0.2753,  0.3866],
        [ 0.3520,  0.0550, -0.1050]])
곱하기:  tensor([[9.3846e-05, 3.8829e-01, 1.3600e-01],
        [3.2190e-01, 5.6849e-01, 4.6046e-01],
        [2.3256e-01, 6.1232e-01, 1.5610e-01]])
나누기:  tensor([[3.1970e-04, 1.0588e+00, 6.5483e+00],
        [2.1183e+00, 6.9550e-01, 1.7548e+00],
        [2.0436e+00, 1.0728e+00, 7.6716e-01]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [17]:
# 여기에 코드를 작성합니다
a = torch.tensor([[1,2,3], [4,5,6]])
b = torch.tensor([[7,8], [9,10], [11,12]])

r = torch.matmul(a, b)
print("내적(행렬 곱): ", r)

내적(행렬 곱):  tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [11]:
# 여기에 코드를 작성합니다
print(r)
r = r + 10
print(r)
r = torch.clamp(r, max=100)
print(r)

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [18]:
# 여기에 코드를 작성합니다
M = torch.tensor([[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]])

print("Column sum:", torch.sum(M, dim=0))

Column sum:  tensor([55, 60, 65, 70, 75])
