## PyTorch Quiz 2 : 연산

In [3]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [22]:
# 여기에 코드를 작성합니다
tensor = torch.tensor([2, 4, 6])
print("plus 5:", tensor + 5)
print("minus 3:", tensor - 3)

plus 5: tensor([ 7,  9, 11])
minus 3: tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [23]:
# 여기에 코드를 작성합니다
a = torch.rand(3, 3)
b = torch.rand(3, 3)

print(a)
print(b)

print("더하기:", a + b)
print("빼기:", a - b)
print("곱하기:", a * b)
print("나누기:", a / b)

tensor([[0.0301, 0.8680, 0.1041],
        [0.1459, 0.9108, 0.2373],
        [0.4190, 0.3140, 0.8440]])
tensor([[0.0258, 0.4953, 0.7385],
        [0.6773, 0.5488, 0.4638],
        [0.0916, 0.5415, 0.6859]])
더하기: tensor([[0.0559, 1.3633, 0.8426],
        [0.8232, 1.4596, 0.7011],
        [0.5107, 0.8555, 1.5299]])
빼기: tensor([[ 0.0043,  0.3728, -0.6344],
        [-0.5313,  0.3620, -0.2265],
        [ 0.3274, -0.2275,  0.1582]])
곱하기: tensor([[0.0008, 0.4299, 0.0769],
        [0.0988, 0.4999, 0.1101],
        [0.0384, 0.1700, 0.5789]])
나누기: tensor([[1.1646, 1.7526, 0.1409],
        [0.2155, 1.6596, 0.5117],
        [4.5736, 0.5798, 1.2306]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [20]:
# 여기에 코드를 작성합니다                                               
a = torch.tensor([[1,2,3], [4,5,6]])
b = torch.tensor([[7,8], [9,10], [11,12]])

r = torch.matmul(a, b)
print("내적(행렬 곱):", r)

내적(행렬 곱): tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [11]:
# 여기에 코드를 작성합니다
print(r)
r = r + 10
print(r)
r = torch.clamp(r, max=100)
print(r)

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [19]:
# 여기에 코드를 작성합니다
M = torch.tensor([[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]])

print("Column sum:", torch.sum(M, dim=0))

Column sum: tensor([55, 60, 65, 70, 75])
