In [1]:
import torch
print("setting complete.")

setting complete.


### 문제1
- 2차원 텐서 [[1, 2, 3], [4, 5, 6]]를 3x2 텐서로 변환해서 출력하세요.

In [2]:
# 여기에 코드를 작성합니다
t = torch.tensor([[1,2,3], [4,5,6]])

ts = t.view(3,2)
print(ts)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


### 문제2
- 단일 값 텐서 tensor(42)에서 값을 추출하고 데이터 타입을 확인해서 출력하세요.

In [4]:
# 여기에 코드를 작성합니다
t = torch.tensor(42)
# (1) 값을 추출하고
value = t
# (2) 데이터 타입을 확인하세요.
value.item()

42

### 문제 3
- 3차원 텐서 [[[1, 2, 3]]]에서 크기가 1인 차원을 제거해서 출력하세요.

In [6]:
# 여기에 코드를 작성합니다
t = torch.tensor([[[1,2,3]]])

ts = torch.squeeze(t)
print(ts)

tensor([1, 2, 3])


### 문제 4
- 1차원 텐서 [1, 2, 3]에 새로운 차원을 추가하여 2차원 텐서로 만들어 출력하세요.

In [7]:
# 여기에 코드를 작성합니다
t = torch.tensor([1,2,3])

tu = torch.unsqueeze(t, dim=0)
print(tu)

tensor([[1, 2, 3]])


### 문제 5
- 두 텐서 a = [1, 2]와 b = [3, 4]를 쌓아 2x2 텐서를 생성해서 출력하세요.


In [8]:
# 여기에 코드를 작성합니다
a = torch.tensor([1,2])
b = torch.tensor([3,4])

stacker = torch.stack([a,b])
print(stacker)

tensor([[1, 2],
        [3, 4]])


### 문제 6
- 두 텐서 a = [[1, 2], [3, 4]]와 b = [[5, 6], [7, 8]]를 열 방향으로 연결해서 출력하세요.

In [32]:
# 여기에 코드를 작성합니다
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5,6], [7,8]])


stacker = torch.stack([a,b], dim=1)
stacker = stacker.view(2, 4)
print(stacker)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### 문제 7
- 텐서 [[1, 2, 3], [4, 5, 6]]를 2개의 조각으로 나눠서 출력해보세요. (행 기준).

In [16]:
# 여기에 코드를 작성합니다
t = torch.tensor([[1,2,3], [4,5,6]])

a, b = torch.chunk(t, 2, dim=0)
print(a, b)

tensor([[1, 2, 3]]) tensor([[4, 5, 6]])


### 문제8
- 텐서 [1, 2, 3, 4, 5]를 각각 2, 2, 1의 크기로 나눠서 출력해보세요.

In [18]:
# 여기에 코드를 작성합니다
t = torch.tensor([1,2,3,4,5])

a, b, c = torch.split(t, 2)
print(a, b, c)

tensor([1, 2]) tensor([3, 4]) tensor([5])


### 문제9
- 텐서 [[1, 2], [3, 4], [5, 6]]에서:
- dim=1 기준으로 크기 1씩 나누세요.
- 각각의 조각을 새로운 축에 쌓은 후 출력해보세요.

In [26]:
# 여기에 코드를 작성합니다
# 1. 열 기준으로 크기 1씩 나누기
t = torch.tensor([[1,2], [3,4], [5,6]])
a,b = torch.split(t, 1, dim=1)
print("Split Result:\n", a, b)
# 2. 새로운 축에 쌓기
ts = torch.stack([a,b])
print("Stack Result:\n", ts)

Split Result:
 tensor([[1],
        [3],
        [5]]) tensor([[2],
        [4],
        [6]])
Stack Result:
 tensor([[[1],
         [3],
         [5]],

        [[2],
         [4],
         [6]]])


### 문제10
- 다음 텐서를 활용해서 아래 문제를 해결해보세요
  ```
  a = torch.tensor([[1, 2], [3, 4]])
  b = torch.tensor([[5, 6], [7, 8]])
  ```

1. 두 텐서를 열 기준으로 연결하고 결과를 출력하세요.
2. 연결된 텐서를 크기 `(4, 2)`로 변환하세요.
3. 변환된 텐서를 2개의 조각으로 나누고, 각 조각을 0번 축으로 스택하여 출력하세요.


In [31]:
# 여기에 코드를 작성합니다
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
# 1. 열 기준으로 병합
ts = torch.stack([a, b], dim=1)
ts = ts.view(2, 4)
print("Concatenated Tensor:\n", ts)
# 2. 크기 (4, 2)로 변환
tv = ts.view(4, 2)
print("Reshaped Tensor:\n", tv)
# 3. 2개의 조각으로 나누고
ta, tb = torch.chunk(tv, 2)
# 4. 0번 축으로 스택
tss = torch.stack([ta, tb], dim=0)
print("Stacked Result:\n", tss)

Concatenated Tensor:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Reshaped Tensor:
 tensor([[1, 2],
        [5, 6],
        [3, 4],
        [7, 8]])
Stacked Result:
 tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
